In [2]:
import subprocess
subprocess.run(["pip", "install", "mlflow", "feast[redis]", "xgboost", "lightgbm", "scikit-learn", "imbalanced-learn", "shap", "optuna"], capture_output=False)

CompletedProcess(args=['pip', 'install', 'mlflow', 'feast[redis]', 'xgboost', 'lightgbm', 'scikit-learn', 'imbalanced-learn', 'shap', 'optuna'], returncode=0)

In [ ]:
import os
os.environ["MLFLOW_S3_ENDPOINT_URL"] = "http://minio:9000"
os.environ["AWS_ACCESS_KEY_ID"] = "minioadmin"
os.environ["AWS_SECRET_ACCESS_KEY"] = "minioadmin"

import mlflow
import mlflow.sklearn
import pandas as pd
import numpy as np
from feast import FeatureStore

# Connect to MLflow
mlflow.set_tracking_uri("http://mlflow:5000")
mlflow.set_experiment("fraud-detection")

print(f"✅ MLflow tracking URI: {mlflow.get_tracking_uri()}")

# Load feature store
store = FeatureStore(repo_path="/home/jovyan/work/feature_store/feature_repo")
print("✅ Feature store connected")

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_9649/571277633.py", line 1, in <module>
    import mlflow
  File "/opt/conda/lib/python3.11/site-packages/mlflow/__init__.py", line 44, in <module>
    from mlflow import (
  File "/opt/conda/lib/python3.11/site-packages/mlflow/artifacts/__init__.py", line 14, in <module>
    from mlflow.tracking import _get_store
  File "/opt/conda/lib/python3.11/site-packages/mlflow/tracking/__init__.py", line 33, in <module>
    from mlflow.tracking.client import MlflowClient
  File "/opt/conda/lib/python3.11/site-packages/mlflow/tracking/client.py", line 27, in <module>
    from mlflow.entities import (
  File "/opt/conda/lib/python3.11/site-packages/mlflow/entities/__init__.py", line 198, in __getattr__
    from mlflow.entities.evaluation_dataset import EvaluationDataset
  File "/opt/conda/lib/python3.11/site-packages/mlflow/entities/evaluation_dataset.py", line 7, in <module>
    from mlflow.data import Dataset
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/__init__.py", line 4, in <module>
    from mlflow.data import dataset_registry
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/dataset_registry.py", line 145, in <module>
    from mlflow.data.pandas_dataset import from_pandas
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/pandas_dataset.py", line 6, in <module>
    import pandas as pd
  File "/opt/conda/lib/python3.11/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 65, in <module>
    from pandas.core import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/ops/__init__.py", line 9, in <module>
    from pandas.core.ops.array_ops import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 55, in <module>
    from pandas.core.computation import expressions
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 23, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/opt/conda/lib/python3.11/site-packages/pandas/compat/_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.11/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_9649/571277633.py", line 1, in <module>
    import mlflow
  File "/opt/conda/lib/python3.11/site-packages/mlflow/__init__.py", line 44, in <module>
    from mlflow import (
  File "/opt/conda/lib/python3.11/site-packages/mlflow/artifacts/__init__.py", line 14, in <module>
    from mlflow.tracking import _get_store
  File "/opt/conda/lib/python3.11/site-packages/mlflow/tracking/__init__.py", line 33, in <module>
    from mlflow.tracking.client import MlflowClient
  File "/opt/conda/lib/python3.11/site-packages/mlflow/tracking/client.py", line 27, in <module>
    from mlflow.entities import (
  File "/opt/conda/lib/python3.11/site-packages/mlflow/entities/__init__.py", line 198, in __getattr__
    from mlflow.entities.evaluation_dataset import EvaluationDataset
  File "/opt/conda/lib/python3.11/site-packages/mlflow/entities/evaluation_dataset.py", line 7, in <module>
    from mlflow.data import Dataset
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/__init__.py", line 4, in <module>
    from mlflow.data import dataset_registry
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/dataset_registry.py", line 145, in <module>
    from mlflow.data.pandas_dataset import from_pandas
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/pandas_dataset.py", line 6, in <module>
    import pandas as pd
  File "/opt/conda/lib/python3.11/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 79, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/masked.py", line 56, in <module>
    from pandas.core import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/nanops.py", line 54, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/opt/conda/lib/python3.11/site-packages/pandas/compat/_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.11/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

2026/05/27 01:00:39 INFO mlflow.tracking.fluent: Experiment with name 'fraud-detection' does not exist. Creating a new experiment.

✅ MLflow tracking URI: http://mlflow:5000

FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/feature_store/feature_repo/feature_store.yaml'

In [4]:
import subprocess
subprocess.run(["pip", "install", "--upgrade", "numpy", "pandas"], capture_output=False)

CompletedProcess(args=['pip', 'install', '--upgrade', 'numpy', 'pandas'], returncode=0)

In [ ]:
import subprocess
subprocess.run(["pip", "install", "--upgrade", "numpy", "pandas", "mlflow", "feast[redis]", "xgboost", "lightgbm", "scikit-learn", "imbalanced-learn", "shap", "optuna"])
print("✅ Done")

In [2]:
import subprocess
subprocess.run(["pip", "install", "--upgrade", "numpy", "pandas", "mlflow", "feast[redis]", 
                "xgboost", "lightgbm", "scikit-learn", "imbalanced-learn", "shap", "optuna"])

import mlflow
import mlflow.sklearn
import pandas as pd
import numpy as np
from feast import FeatureStore

mlflow.set_tracking_uri("http://mlflow:5000")
mlflow.set_experiment("fraud-detection")

print(f"✅ MLflow tracking URI: {mlflow.get_tracking_uri()}")

store = FeatureStore(repo_path="/home/jovyan/work/feature_store/feature_repo")
print("✅ Feature store connected")

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_908/1682673576.py", line 5, in <module>
    import mlflow
  File "/opt/conda/lib/python3.11/site-packages/mlflow/__init__.py", line 44, in <module>
    from mlflow import (
  File "/opt/conda/lib/python3.11/site-packages/mlflow/artifacts/__init__.py", line 14, in <module>
    from mlflow.tracking import _get_store
  File "/opt/conda/lib/python3.11/site-packages/mlflow/tracking/__init__.py", line 33, in <module>
    from mlflow.tracking.client import MlflowClient
  File "/opt/conda/lib/python3.11/site-packages/mlflow/tracking/client.py", line 27, in <module>
    from mlflow.entities import (
  File "/opt/conda/lib/python3.11/site-packages/mlflow/entities/__init__.py", line 198, in __getattr__
    from mlflow.entities.evaluation_dataset import EvaluationDataset
  File "/opt/conda/lib/python3.11/site-packages/mlflow/entities/evaluation_dataset.py", line 7, in <module>
    from mlflow.data import Dataset
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/__init__.py", line 4, in <module>
    from mlflow.data import dataset_registry
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/dataset_registry.py", line 145, in <module>
    from mlflow.data.pandas_dataset import from_pandas
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/pandas_dataset.py", line 6, in <module>
    import pandas as pd
  File "/opt/conda/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 53, in <module>
    from pandas.core import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/opt/conda/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.11/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/conda/lib/python3.11/site-packages/traitlets/config/application.py", line 1053, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/opt/conda/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "/opt/conda/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/conda/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_908/1682673576.py", line 5, in <module>
    import mlflow
  File "/opt/conda/lib/python3.11/site-packages/mlflow/__init__.py", line 44, in <module>
    from mlflow import (
  File "/opt/conda/lib/python3.11/site-packages/mlflow/artifacts/__init__.py", line 14, in <module>
    from mlflow.tracking import _get_store
  File "/opt/conda/lib/python3.11/site-packages/mlflow/tracking/__init__.py", line 33, in <module>
    from mlflow.tracking.client import MlflowClient
  File "/opt/conda/lib/python3.11/site-packages/mlflow/tracking/client.py", line 27, in <module>
    from mlflow.entities import (
  File "/opt/conda/lib/python3.11/site-packages/mlflow/entities/__init__.py", line 198, in __getattr__
    from mlflow.entities.evaluation_dataset import EvaluationDataset
  File "/opt/conda/lib/python3.11/site-packages/mlflow/entities/evaluation_dataset.py", line 7, in <module>
    from mlflow.data import Dataset
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/__init__.py", line 4, in <module>
    from mlflow.data import dataset_registry
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/dataset_registry.py", line 145, in <module>
    from mlflow.data.pandas_dataset import from_pandas
  File "/opt/conda/lib/python3.11/site-packages/mlflow/data/pandas_dataset.py", line 6, in <module>
    import pandas as pd
  File "/opt/conda/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 67, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/arrays/masked.py", line 61, in <module>
    from pandas.core import (
  File "/opt/conda/lib/python3.11/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/opt/conda/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.11/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

✅ MLflow tracking URI: http://mlflow:5000
✅ Feature store connected

In [3]:
# Load silver paysim data
df = pd.read_parquet("/home/jovyan/work/data/silver/paysim/paysim.parquet")
print(f"✅ Loaded {df.shape[0]:,} rows, {df.shape[1]} columns")
print(f"Fraud rate: {df['isFraud'].mean():.4f} ({df['isFraud'].sum():,} fraud cases)")
df.head(3)

✅ Loaded 6,362,620 rows, 18 columns
Fraud rate: 0.0013 (8,213 fraud cases)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,transaction_id,ingestion_ts,source,transaction_date,balance_diff_orig,balance_diff_dest,processed_ts
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0,C1231006815,2026-05-25T21:42:31.068737,paysim,2024-01-01,-9839.64,0.0,2026-05-25T21:51:57.616264
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0,C1666544295,2026-05-25T21:42:31.068737,paysim,2024-01-01,-1864.28,0.0,2026-05-25T21:51:57.616264
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0,C1305486145,2026-05-25T21:42:31.068737,paysim,2024-01-01,-181.00,0.0,2026-05-25T21:51:57.616264

In [1]:
import subprocess
subprocess.run(["pip", "install", "mlflow", "feast[redis]", "xgboost", "lightgbm", "scikit-learn", "imbalanced-learn", "shap", "optuna"])

import mlflow
import mlflow.sklearn
import pandas as pd
import numpy as np
from feast import FeatureStore

mlflow.set_tracking_uri("http://mlflow:5000")
mlflow.set_experiment("fraud-detection")

print(f"✅ MLflow tracking URI: {mlflow.get_tracking_uri()}")

store = FeatureStore(repo_path="/home/jovyan/work/feature_store/feature_repo")
print("✅ Feature store connected")

✅ MLflow tracking URI: http://mlflow:5000
✅ Feature store connected

In [2]:
df = pd.read_parquet("/home/jovyan/work/data/silver/paysim/paysim.parquet")
print(f"✅ Loaded {df.shape[0]:,} rows, {df.shape[1]} columns")
print(f"Fraud rate: {df['isFraud'].mean():.4f} ({df['isFraud'].sum():,} fraud cases)")
df.head(3)

✅ Loaded 6,362,620 rows, 18 columns
Fraud rate: 0.0013 (8,213 fraud cases)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,transaction_id,ingestion_ts,source,transaction_date,balance_diff_orig,balance_diff_dest,processed_ts
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0,C1231006815,2026-05-25T21:42:31.068737,paysim,2024-01-01,-9839.64,0.0,2026-05-25T21:51:57.616264
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0,C1666544295,2026-05-25T21:42:31.068737,paysim,2024-01-01,-1864.28,0.0,2026-05-25T21:51:57.616264
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0,C1305486145,2026-05-25T21:42:31.068737,paysim,2024-01-01,-181.00,0.0,2026-05-25T21:51:57.616264

In [3]:
from sklearn.preprocessing import LabelEncoder

# Select relevant features
features = ['type', 'amount', 'oldbalanceOrg', 'newbalanceOrig', 
            'oldbalanceDest', 'newbalanceDest', 'balance_diff_orig', 
            'balance_diff_dest']
target = 'isFraud'

# Encode transaction type
le = LabelEncoder()
df['type_encoded'] = le.fit_transform(df['type'])

feature_cols = ['type_encoded', 'amount', 'oldbalanceOrg', 'newbalanceOrig',
                'oldbalanceDest', 'newbalanceDest', 'balance_diff_orig', 'balance_diff_dest']

X = df[feature_cols]
y = df[target]

print(f"✅ Features shape: {X.shape}")
print(f"Class distribution:\n{y.value_counts()}")
print(f"Fraud rate: {y.mean():.4f}")

✅ Features shape: (6362620, 8)
Class distribution:
isFraud
0    6354407
1       8213
Name: count, dtype: int64
Fraud rate: 0.0013

In [4]:
from sklearn.model_selection import train_test_split

# Time-based split — never random for fraud detection
# Use step column as time proxy (higher step = later in time)
split_idx = int(len(df) * 0.8)
df_sorted = df.sort_values('step').reset_index(drop=True)

X_train = df_sorted[feature_cols].iloc[:split_idx]
y_train = df_sorted[target].iloc[:split_idx]
X_test = df_sorted[feature_cols].iloc[split_idx:]
y_test = df_sorted[target].iloc[split_idx:]

print(f"✅ Train: {X_train.shape[0]:,} rows | Fraud: {y_train.sum():,} ({y_train.mean():.4f})")
print(f"✅ Test:  {X_test.shape[0]:,} rows  | Fraud: {y_test.sum():,} ({y_test.mean():.4f})")

✅ Train: 5,090,096 rows | Fraud: 3,959 (0.0008)
✅ Test:  1,272,524 rows  | Fraud: 4,254 (0.0033)

In [8]:
mlflow.set_tracking_uri("http://mlflow:5000")
mlflow.set_experiment("fraud-detection")

2026/05/27 02:03:48 INFO mlflow.tracking.fluent: Experiment with name 'fraud-detection' does not exist. Creating a new experiment.

<Experiment: artifact_location='s3://mlflow/artifacts/1', creation_time=1779847428914, experiment_id='1', last_update_time=1779847428914, lifecycle_stage='active', name='fraud-detection', tags={}, trace_location=None, workspace='default'>

In [10]:
print(f"PR-AUC: {pr_auc:.4f}")
print(f"F1: {f1:.4f}")

PR-AUC: 0.6491
F1: 0.1647

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, average_precision_score, f1_score

model = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

pr_auc = average_precision_score(y_test, y_prob)
f1 = f1_score(y_test, y_pred)

print(f"✅ PR-AUC: {pr_auc:.4f}")
print(f"✅ F1: {f1:.4f}")
print(classification_report(y_test, y_pred, target_names=['legit', 'fraud']))

✅ PR-AUC: 0.6491
✅ F1: 0.1647
              precision    recall  f1-score   support

       legit       1.00      0.97      0.98   1268270
       fraud       0.09      0.89      0.16      4254

    accuracy                           0.97   1272524
   macro avg       0.55      0.93      0.57   1272524
weighted avg       1.00      0.97      0.98   1272524

In [13]:
import subprocess
subprocess.run(["pip", "install", "boto3"])

CompletedProcess(args=['pip', 'install', 'boto3'], returncode=0)

In [15]:
import os
os.environ["MLFLOW_S3_ENDPOINT_URL"] = "http://minio:9000"
os.environ["AWS_ACCESS_KEY_ID"] = "minioadmin"
os.environ["AWS_SECRET_ACCESS_KEY"] = "minioadmin"

In [16]:
import os
import pickle

# Save model locally first
os.makedirs("/home/jovyan/work/data/models", exist_ok=True)
with open("/home/jovyan/work/data/models/logistic_regression.pkl", "wb") as f:
    pickle.dump(model, f)

# Log as artifact instead of log_model
with mlflow.start_run(run_name="baseline_logistic_regression"):
    mlflow.log_param("model", "logistic_regression")
    mlflow.log_param("class_weight", "balanced")
    mlflow.log_metric("pr_auc", pr_auc)
    mlflow.log_metric("f1", f1)
    mlflow.log_artifact("/home/jovyan/work/data/models/logistic_regression.pkl")
    print("✅ Run logged to MLflow")
    print(f"PR-AUC: {pr_auc:.4f} | F1: {f1:.4f}")

✅ Run logged to MLflow
PR-AUC: 0.6491 | F1: 0.1647
🏃 View run baseline_logistic_regression at: http://mlflow:5000/#/experiments/1/runs/14d959192cc04225aa38061029e4352f
🧪 View experiment at: http://mlflow:5000/#/experiments/1